/*Student table*/

CREATE TABLE "STUDENT"
( "S_ID" VARCHAR2(10) NOT NULL ENABLE,
"S_NAME" VARCHAR2(40),
"S_DEPT" VARCHAR2(10),
"S_CONTACT" VARCHAR2(15),
"S_EMAIL" VARCHAR2(30),
"CGPA" NUMBER NOT NULL ENABLE,
CONSTRAINT "STUDENT_PK" PRIMARY KEY ("S_ID") ENABLE

)
/

/*Teacher table*/

CREATE TABLE "TEACHER"
( "T_ID" VARCHAR2(10) NOT NULL ENABLE,
"S_ID" VARCHAR2(10),
"T_NAME" VARCHAR2(40),
"T_EMAIL" VARCHAR2(30),
"T_ADDRESS" VARCHAR2(40),
CONSTRAINT "TEACHER_PK" PRIMARY KEY ("T_ID") ENABLE,
CONSTRAINT "TEACHER_FK" FOREIGN KEY ("S_ID")
REFERENCES "STUDENT" ("S_ID") ENABLE
)
/

/*Course table*/

CREATE TABLE "COURSE"
( "C_ID" VARCHAR2(10),
"C_NAME" VARCHAR2(40),
"C_CREDIT" VARCHAR2(10),
"S_ID" VARCHAR2(10),
CONSTRAINT "COURSE_PK" PRIMARY KEY ("C_ID") ENABLE,
CONSTRAINT "COURSE_FK" FOREIGN KEY ("S_ID")
REFERENCES "STUDENT" ("S_ID") ENABLE
)
/

/*Advisor table*/

CREATE TABLE "ADVISOR"
( "A_ID" VARCHAR2(10) NOT NULL ENABLE,
"A_NAME" VARCHAR2(40),
"A_EMAIL" VARCHAR2(30),
"A_CONTACT" VARCHAR2(15),
"S_ID" VARCHAR2(10),
CONSTRAINT "ADVISOR_PK" PRIMARY KEY ("A_ID") ENABLE,
CONSTRAINT "ADVISOR_FK" FOREIGN KEY ("S_ID")
REFERENCES "STUDENT" ("S_ID") ENABLE
)
/

/*Fees*/

CREATE TABLE "FEES"
( "FEE_ID" VARCHAR2(10) NOT NULL ENABLE,
"FEE_AMOUNT" VARCHAR2(20),
"C_ID" VARCHAR2(10),
CONSTRAINT "FEES_PK" PRIMARY KEY ("FEE_ID") ENABLE,
CONSTRAINT "FEES_CK1" CHECK (FEE_AMOUNT >= 0) ENABLE,
CONSTRAINT "FEES_FK" FOREIGN KEY ("C_ID")
REFERENCES "COURSE" ("C_ID") ENABLE
)
/

/*Feedback*/

CREATE TABLE "FEEDBACK"
( "FD_ID" VARCHAR2(10) NOT NULL ENABLE,
"FD_REPORT" VARCHAR2(40),
"S_ID" VARCHAR2(10),
"C_ID" VARCHAR2(10),
"A_ID" VARCHAR2(10),
CONSTRAINT "FEEDBACK_PK" PRIMARY KEY ("FD_ID") ENABLE,
CONSTRAINT "FEEDBACK_FK" FOREIGN KEY ("S_ID")
REFERENCES "STUDENT" ("S_ID") ENABLE,
CONSTRAINT "FEEDBACK_FK2" FOREIGN KEY ("C_ID")
REFERENCES "COURSE" ("C_ID") ENABLE,
CONSTRAINT "FEEDBACK_FK3" FOREIGN KEY ("A_ID")
REFERENCES "ADVISOR" ("A_ID") ENABLE
)
/